server:
  port: 0

spring:
  application:
    name: "core"
  datasource:
      url: jdbc:postgresql://localhost:5432/core-db
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver


eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    instance-id: "${spring.application.name}:${random.value}"



