server:
  port: 8888

spring:
  application:
    name: "config-service"
  cloud:
    config:
      server:
        git:
          uri: "file://${user.home}/config-repo"


eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
